name : create a comment on new issues 
on:
  issues:
    types:[opened]
 
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: "dump github context"
          run: echo '${{toJSON{github.event}}}' |jq
          shell: bash
  
  
